version: '3.8'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-no-reply@supporthub.local}
      - SUPPORT_TEAM_EMAIL=${SUPPORT_TEAM_EMAIL:-support@example.com}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - SUPPORT_FORWARD_NUMBER=${SUPPORT_FORWARD_NUMBER}
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: supporthub_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supporthub_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
